apiVersion: v1
kind: Service
metadata:
  name: udp-demo-server
  labels:
    app: udp-demo
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 9090
  selector:
    app: udp-demo
    tier: backend
